language: python
python:
  - "2.7"

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pep8

install:
  - "pip install tox"

script:
<<<<<<< HEAD
  - "./run_tests.sh -N --no-pep8"
=======
  - NOSE_VERBOSE=0 tox -e $TOX_ENV

sudo: false
>>>>>>> c0723eb0a632870a3077c2513aee7ed51cb31779
